/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Blog API
 * OrvalForge Demo - 一个完整的博客 API 示例
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
export type GetPostsParams = {
/**
 * 页码
 */
page?: number;
/**
 * 每页数量
 */
limit?: number;
/**
 * 按用户 ID 筛选
 */
userId?: number;
};

export type GetUsersParams = {
/**
 * 页码，从 1 开始
 */
page?: number;
/**
 * 每页数量
 */
limit?: number;
};

/**
 * 错误详情
 */
export type ErrorResponseDetails = { [key: string]: unknown };

/**
 * 错误响应
 */
export interface ErrorResponse {
  /** 错误代码 */
  code?: string;
  /** 错误详情 */
  details?: ErrorResponseDetails;
  /** 错误信息 */
  error: string;
}

/**
 * 创建评论请求
 */
export interface CreateCommentRequest {
  /**
   * 评论内容
   * @minLength 1
   * @maxLength 1000
   */
  body: string;
  /** 评论者邮箱 */
  email: string;
  /**
   * 评论者姓名
   * @minLength 1
   * @maxLength 100
   */
  name: string;
}

/**
 * 评论信息
 */
export interface Comment {
  /** 评论内容 */
  body: string;
  /** 评论者邮箱 */
  email: string;
  /** 评论 ID */
  id: number;
  /** 评论者姓名 */
  name: string;
  /** 文章 ID */
  postId: number;
}

/**
 * 更新文章请求
 */
export interface UpdatePostRequest {
  /**
   * 文章内容
   * @minLength 1
   */
  body?: string;
  /**
   * 文章标题
   * @minLength 1
   * @maxLength 200
   */
  title?: string;
}

/**
 * 创建文章请求
 */
export interface CreatePostRequest {
  /**
   * 文章内容
   * @minLength 1
   */
  body: string;
  /**
   * 文章标题
   * @minLength 1
   * @maxLength 200
   */
  title: string;
  /**
   * 作者用户 ID
   * @minimum 1
   */
  userId: number;
}

/**
 * 文章信息
 */
export interface Post {
  /** 文章内容 */
  body: string;
  /** 文章 ID */
  id: number;
  /** 文章标题 */
  title: string;
  /** 作者用户 ID */
  userId: number;
}

/**
 * 更新用户请求
 */
export interface UpdateUserRequest {
  /** 邮箱地址 */
  email?: string;
  /**
   * 用户姓名
   * @minLength 1
   * @maxLength 100
   */
  name?: string;
  /** 手机号码 */
  phone?: string;
  /**
   * 用户名
   * @minLength 3
   * @maxLength 50
   * @pattern ^[a-zA-Z0-9_]+$
   */
  username?: string;
  /** 个人网站 */
  website?: string;
}

/**
 * 创建用户请求
 */
export interface CreateUserRequest {
  /** 邮箱地址 */
  email: string;
  /**
   * 用户姓名
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /**
   * 手机号码
   * @pattern ^1[3-9]\d{9}$
   */
  phone?: string;
  /**
   * 用户名
   * @minLength 3
   * @maxLength 50
   * @pattern ^[a-zA-Z0-9_]+$
   */
  username: string;
  /** 个人网站 */
  website?: string;
}

/**
 * 公司信息
 */
export interface Company {
  /** 业务描述 */
  bs?: string;
  /** 公司口号 */
  catchPhrase?: string;
  /** 公司名称 */
  name?: string;
}

/**
 * 地理位置
 */
export interface GeoLocation {
  /** 纬度 */
  lat?: string;
  /** 经度 */
  lng?: string;
}

/**
 * 地址信息
 */
export interface Address {
  /** 城市 */
  city?: string;
  geo?: GeoLocation;
  /** 街道地址 */
  street?: string;
  /** 门牌号/套房号 */
  suite?: string;
  /** 邮政编码 */
  zipcode?: string;
}

/**
 * 用户信息
 */
export interface User {
  address?: Address;
  company?: Company;
  /** 邮箱地址 */
  email: string;
  /** 用户 ID */
  id: number;
  /** 用户姓名 */
  name: string;
  /** 手机号码 */
  phone?: string;
  /** 用户名 */
  username: string;
  /** 个人网站 */
  website?: string;
}





  /**
 * 获取所有用户的列表，支持分页
 * @summary 获取用户列表
 */
export const getUsers = <TData = AxiosResponse<User[]>>(
    params?: GetUsersParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/users`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 创建一个新用户
 * @summary 创建用户
 */
export const createUser = <TData = AxiosResponse<User>>(
    createUserRequest: CreateUserRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/users`,
      createUserRequest,options
    );
  }

/**
 * 根据用户 ID 获取用户详细信息
 * @summary 获取用户详情
 */
export const getUserById = <TData = AxiosResponse<User>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/users/${id}`,options
    );
  }

/**
 * 更新指定用户的信息
 * @summary 更新用户
 */
export const updateUser = <TData = AxiosResponse<User>>(
    id: number,
    updateUserRequest: UpdateUserRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/users/${id}`,
      updateUserRequest,options
    );
  }

/**
 * 删除指定的用户
 * @summary 删除用户
 */
export const deleteUser = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/users/${id}`,options
    );
  }

/**
 * 获取所有文章的列表，支持分页和筛选
 * @summary 获取文章列表
 */
export const getPosts = <TData = AxiosResponse<Post[]>>(
    params?: GetPostsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/posts`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 创建一篇新文章
 * @summary 创建文章
 */
export const createPost = <TData = AxiosResponse<Post>>(
    createPostRequest: CreatePostRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/posts`,
      createPostRequest,options
    );
  }

/**
 * 根据文章 ID 获取文章详细信息
 * @summary 获取文章详情
 */
export const getPostById = <TData = AxiosResponse<Post>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/posts/${id}`,options
    );
  }

/**
 * 更新指定文章的信息
 * @summary 更新文章
 */
export const updatePost = <TData = AxiosResponse<Post>>(
    id: number,
    updatePostRequest: UpdatePostRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/posts/${id}`,
      updatePostRequest,options
    );
  }

/**
 * 删除指定的文章
 * @summary 删除文章
 */
export const deletePost = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/posts/${id}`,options
    );
  }

/**
 * 获取指定文章的所有评论
 * @summary 获取文章评论
 */
export const getPostComments = <TData = AxiosResponse<Comment[]>>(
    postId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/posts/${postId}/comments`,options
    );
  }

/**
 * 为指定文章添加一条评论
 * @summary 添加评论
 */
export const createComment = <TData = AxiosResponse<Comment>>(
    postId: number,
    createCommentRequest: CreateCommentRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/posts/${postId}/comments`,
      createCommentRequest,options
    );
  }

export type GetUsersResult = AxiosResponse<User[]>
export type CreateUserResult = AxiosResponse<User>
export type GetUserByIdResult = AxiosResponse<User>
export type UpdateUserResult = AxiosResponse<User>
export type DeleteUserResult = AxiosResponse<void>
export type GetPostsResult = AxiosResponse<Post[]>
export type CreatePostResult = AxiosResponse<Post>
export type GetPostByIdResult = AxiosResponse<Post>
export type UpdatePostResult = AxiosResponse<Post>
export type DeletePostResult = AxiosResponse<void>
export type GetPostCommentsResult = AxiosResponse<Comment[]>
export type CreateCommentResult = AxiosResponse<Comment>
