/**
 * 预期生成的 API 接口函数示例
 * 这个文件展示了 OrvalForge 应该生成的 TypeScript API 函数格式
 */

import type { 
  Pet, 
  NewPet, 
  UpdatePet, 
  Pets, 
  User, 
  NewUser, 
  UserList, 
  Error 
} from './models';

// ============================================================================
// Pet API Functions
// ============================================================================

/**
 * List all pets
 * Returns a list of pets with optional filtering
 */
export const listPets = async (params?: {
  limit?: number;
  tags?: string[];
}): Promise<{
  data: Pets;
  headers: { 'x-next'?: string };
}> => {
  // Implementation would be generated by OrvalForge
};

/**
 * Create a pet
 * Creates a new pet in the store
 */
export const createPet = async (data: NewPet): Promise<{
  data: Pet;
}> => {
  // Implementation would be generated by OrvalForge
};

/**
 * Info for a specific pet
 * Returns a single pet
 */
export const showPetById = async (params: {
  petId: number;
}): Promise<{
  data: Pet;
}> => {
  // Implementation would be generated by OrvalForge
};

/**
 * Update a pet
 * Updates an existing pet in the store
 */
export const updatePet = async (params: {
  petId: number;
  data: UpdatePet;
}): Promise<{
  data: Pet;
}> => {
  // Implementation would be generated by OrvalForge
};

/**
 * Delete a pet
 * Deletes a single pet
 */
export const deletePet = async (params: {
  petId: number;
}): Promise<void> => {
  // Implementation would be generated by OrvalForge
};

// ============================================================================
// User API Functions
// ============================================================================

/**
 * List all users
 * Returns a list of users with pagination
 */
export const listUsers = async (params?: {
  page?: number;
  pageSize?: number;
}): Promise<{
  data: UserList;
}> => {
  // Implementation would be generated by OrvalForge
};

/**
 * Create a user
 * Creates a new user
 */
export const createUser = async (data: NewUser): Promise<{
  data: User;
}> => {
  // Implementation would be generated by OrvalForge
};

/**
 * Get user by ID
 * Returns a single user
 */
export const getUserById = async (params: {
  userId: number;
}): Promise<{
  data: User;
}> => {
  // Implementation would be generated by OrvalForge
};